
CREATE TABLE IF NOT EXISTS users (
  id BIGINT NOT NULL generated by default as identity PRIMARY KEY,
  firstname VARCHAR,
  lastname VARCHAR,
  address VARCHAR,
  email VARCHAR,
  phone VARCHAR,
  createdby VARCHAR,
  created_date timestamp,
  modifiedby VARCHAR,
  last_modified_date timestamp
);

CREATE TABLE IF NOT EXISTS user_photos (
  id BIGINT NOT NULL generated by default as identity PRIMARY KEY,
  photo IMAGE NOT NULL
);

CREATE TABLE IF NOT EXISTS auditlog (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  operation VARCHAR,
  event_date timestamp,
  username VARCHAR
);

alter table user_photos add constraint FKcaf6ht0hfw93lwc13ny0sdmvo foreign key (id) references user_photos(id);