
INSERT INTO users(id, name, surname, address, email, phone) VALUES (1,  'Aleksandrs',  'Collins',     'Central Strees 13',                                     'awesomeclient21@gmail.com',  '8000233412');
INSERT INTO users(id, name, surname, address, email, phone) VALUES (2,  'Peteris',     'Klava',       '10 Old Mill Rd, Tomatin, Inverness IV13 7YW, UK',       'TheSickGamer@gmail.com',     '(288) 208-8088');
INSERT INTO users(id, name, surname, address, email, phone) VALUES (3,  'Vladislavs',  'Strass',      '13 Bathurst Rd, Norwich NR2 2PP, UK',                   'Exciting@gmail.com',         '(552) 691-6319');
INSERT INTO users(id, name, surname, address, email, phone) VALUES (4,  'Kenny',       'Jones',       '2 Court Rd, Port Glasgow PA14 5PR, UK',                 'Ashamed@gmail.com',          '(516) 789-5429');
INSERT INTO users(id, name, surname, address, email, phone) VALUES (5,  'Fred',        'Mazur',       '8 Rose Ct, Wickersley, Rotherham S66 1BH, UK',          'Dysfunctional@gmail.com',    '(368) 870-4044');
INSERT INTO users(id, name, surname, address, email, phone) VALUES (6,  'Brian',       'May',         '8 Park Ave, Newport Pagnell MK16 8JE, UK',              'Plastic@gmail.com',          '(363) 649-3522');
INSERT INTO users(id, name, surname, address, email, phone) VALUES (7,  'Dmitry',      'Ivanov',      'Unnamed Road, Sanquhar DG4, UK',                        'Plant@gmail.com',            '(524) 910-4607');
INSERT INTO users(id, name, surname, address, email, phone) VALUES (8,  'Angela',      'Travis',      '18 Weston Rd, Crewe CW1 6FX, UK',                       'Various@gmail.com',          '(610) 307-2244');
INSERT INTO users(id, name, surname, address, email, phone) VALUES (9,  'Monika',      'Smith',       'St Pauls, 8-12 Warwick Ln, London EC4P 4BN, UK',        'Sassy@gmail.com',            '(715) 186-9388');
INSERT INTO users(id, name, surname, address, email, phone) VALUES (10, 'John',        'Mallins',     '109 A38, Exeter EX6, UK',                               'Acceptable@gmail.com',       '(337) 188-1759');
INSERT INTO users(id, name, surname, address, email, phone) VALUES (11, 'Vladimirs',   'Holmogorov',  '11 Dunelm Grange, Boldon Colliery NE35 9AB, UK',        'Cautious@gmail.com',         '(463) 111-9161');